# Write your MySQL query statement below
SELECT DISTINCT P.PRODUCT_ID, P.PRODUCT_NAME
FROM PRODUCT AS P
JOIN SALES AS S ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE SALE_DATE BETWEEN '2019-01-01' AND '2019-03-31' 
AND P.PRODUCT_ID NOT IN(
    SELECT PRODUCT_ID 
    FROM SALES
    WHERE SALE_DATE < '2019-01-01' OR SALE_DATE > '2019-03-31'
)