# Write your MySQL query statement below
SELECT S.NAME
FROM SALESPERSON AS S
WHERE SALES_ID NOT IN(
    SELECT SALES_ID
    FROM ORDERS AS O
    LEFT JOIN COMPANY AS C ON C.COM_ID = O.COM_ID
    WHERE C.NAME = 'RED'
)